apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-scaledobject
  namespace: togglemaster
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 120
  pollingInterval: 15
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: analytics-service-sqs-trigger-auth
      metadata:
        queueURL: ""
        queueLength: "5"
        awsRegion: "us-east-1"

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: analytics-service-sqs-trigger-auth
  namespace: togglemaster
spec:
  podIdentity:
    provider: aws-eks

