apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<seu-usuario>/toggle-master-gitops.git
    targetRevision: main
    path: apps/analytics-service
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
