apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service-sa
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::499743054252:role/togglemaster-evaluation-service-irsa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::499743054252:role/togglemaster-analytics-service-irsa

