apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: togglemaster
  labels:
    app: flag-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
      - name: flag-service
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/flag-service:v1.0.0-bbe9f7e
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: FLAG_SERVICE_PORT
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: AUTH_SERVICE_URL
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flag-service-secrets
              key: DATABASE_URL
        resources:
          requests:
            cpu: 100m
            memory: 96Mi
          limits:
            cpu: 300m
            memory: 192Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
